services:
    php-apache-environment:
        container_name: php-apache
        build:
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "80:80"
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
